site:
  name: 스티키
  site: 'https://sticky-landing.vercel.app/'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: KmwZH2K8WJvF0EZb61TBXcTZzCY5TerUGRjeTLOvA8I

# Default SEO metadata
metadata:
  title:
    default: 스티키 - 상단바 메모 고정 앱
    template: '%s — 스티키'
  description: "메모를 상단바에 고정하고 언제든 확인하세요. 잊으면 안 되는 중요한 할 일을 가장 빠르고 확실하게 관리하는 앱, 스티키."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: 스티키
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image

i18n:
  language: ko
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
